import {StyleSheet} from 'react-native';

const dynamicStyles = (appStyles, colorScheme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      alignItems: 'center',
      backgroundColor: appStyles.colorSet[colorScheme].mainThemeBackgroundColor,
    },
    title: {
      fontSize: 20,
      fontFamily: 'Poppins-Regular',
      fontWeight: '600',
      textAlign: 'left',
      paddingBottom: 5,
      color: appStyles.colorSet[colorScheme].blackColor,
    },
    smTitle: {
      fontSize: 17,
      fontFamily: 'Poppins-Regular',
      fontWeight: '600',
      textAlign: 'left',
      lineHeight: 20,
      marginVertical: 5,
      color: appStyles.colorSet[colorScheme].blackColor,
    },
    topTitle: {
      fontSize: 20,
      fontFamily: 'Poppins-Regular',
      fontWeight: '600',
      textAlign: 'left',
      paddingBottom: 10,
      paddingHorizontal: 5,
      color: appStyles.colorSet[colorScheme].blackColor,
    },
    subTitle: {
      fontSize: 16,
      fontFamily: 'Poppins-Regular',
      fontWeight: '500',
      textAlign: 'left',
      color: appStyles.colorSet[colorScheme].blackColor,
      // paddingBottom : 10,
    },
    text: {
      fontSize: 16,
      fontFamily: 'Poppins-Regular',
      lineHeight: 20,
      fontWeight: '400',
      textAlign: 'left',
      color: appStyles.colorSet[colorScheme].blackColor,
      marginVertical: 5,
    },
    image: {
      width: '100%',
      position: 'absolute',
    },
    flexContainer: {
      flexDirection: 'row',
    },
    conFlexContainer: {
      flexDirection: 'row',
      width: '100%',
      flexWrap: 'wrap',
    },
    topContainer: {
      backgroundColor: appStyles.colorSet[colorScheme].grey0,
      paddingVertical: 20,
      paddingHorizontal: 10,
      marginBottom: 20,
      borderRadius: 10,
    },
    insContainer: {
      padding: 5,
      marginVertical: 5,
      borderColor: appStyles.colorSet[colorScheme].grey9,
      borderRadius: 3,
    },
    boxContainer: {
      width: '90%',
      padding: 20,
      marginTop: 30,
      backgroundColor: 'white',
      borderRadius: 8,
      shadowColor: 'rgba(0,0,0,0.5)',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    boxContainerProcessing: {
      width: '90%',
      padding: 30,
      marginTop: 30,
      backgroundColor: 'white',
      borderRadius: 8,
      shadowColor: 'rgba(0,0,0,0.5)',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    btnContainer: {
      alignItems: 'center',
      alignSelf: 'center',
      marginTop: 40,
      color: '#0A1F44',
      backgroundColor: appStyles.colorSet[colorScheme].mainColor,
      paddingVertical: 13,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: 'white',
      width: '100%',
    },
    btnHalfContainer: {
      alignItems: 'center',
      alignSelf: 'center',
      marginTop: 40,
      color: '#0A1F44',
      backgroundColor: appStyles.colorSet[colorScheme].mainColor,
      paddingVertical: 13,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: 'white',
      width: '50%',
    },
    btnText: {
      fontSize: 15,
      fontWeight: '500',
      lineHeight: 20,
      fontFamily: 'Poppins-Regular',
      color: appStyles.colorSet[colorScheme].mainThemeBackgroundColor,
    },
    inputBox: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderBottomColor: appStyles.colorSet[colorScheme].grey0,
      borderBottomWidth: 1,
    },
    InputContainer: {
      height: 40,
      paddingLeft: 10,
      color: appStyles.colorSet[colorScheme].mainTextColor,
      width: '50%',
      alignSelf: 'flex-end',
      textAlign: 'right',
      borderRadius: 10,
    },

    flagStyle: {
      width: 35,
      height: 25,
      borderColor: appStyles.colorSet[colorScheme].mainTextColor,
    },
    phoneInputTextStyle: {
      borderRightWidth: 0,
      borderLeftWidth: 1,
      borderColor: appStyles.colorSet[colorScheme].grey3,
      height: 42,
      fontSize: 15,
      fontFamily: 'Poppins-Regular',
      color: appStyles.colorSet[colorScheme].mainTextColor,
      borderBottomRightRadius: 0,
      borderTopRightRadius: 0,
      borderBottomLeftRadius: 0,
      borderTopLeftRadius: 0,
      paddingLeft: 10,
    },
    input: {
      flex: 1,
      borderLeftWidth: 1,
      borderRadius: 3,
      borderColor: appStyles.colorSet[colorScheme].grey3,
      color: appStyles.colorSet[colorScheme].mainTextColor,
      fontSize: 17,
      fontFamily: 'Poppins-Regular',
      fontWeight: '700',
      backgroundColor: appStyles.colorSet[colorScheme].mainThemeBackgroundColor,
    },
    btnBack: {
      marginLeft: 20,
    },
  });
};

export default dynamicStyles;
